### ISSUE TITLE
Request to Add "GECal" Package to the "Official Statistics" Task View

### ISSUE THREAD

**Issue by yonghyun-K** [cran-task-views/OfficialStatistics#35]
I propose adding the GECal package to the Weighting and Calibration section (4.1) of the "Official Statistics" task view.

GECal produces calibration weights using generalized entropy as the objective function for optimization.

You can find more details about the package here: [GECal on CRAN](https://cran.r-project.org/package=GECal).

Thank you for considering this request.

**Comment by matthias-da** [comment]
Thanks, is submitted and it's on the way to CRAN.

**Comment by yonghyun-K** [comment]
Thank you for your assistance!
