### ISSUE TITLE
Package 'IC2' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/OfficialStatistics#5]
Package [IC2](https://CRAN.R-project.org/package=IC2) is currently listed in CRAN Task View [OfficialStatistics](https://CRAN.R-project.org/view=OfficialStatistics) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
I wanted to check what the status here is. We had asked for a resolution within four weeks and three weeks already passed. Was there any contact with the maintainer or should the package be removed by the end of the week?

**Comment by matthias-da** [comment]
Status quo. I also contacted the authors. Lets wait for a few days and we will clean up the ctv next week.

**Comment by zeileis** [comment]
Perfect, thanks for the info, Matthias @matthias-da !

**Comment by matthias-da** [comment]
removed from ctv OfficialStatistics
